INSERT INTO test.kullanicilar (id, name, l_name, b_date) VALUES (uuid(), 'Fernando', 'Alonso', '1981-07-29');
INSERT INTO test.kullanicilar (id, name, l_name, b_date) VALUES (uuid(), 'Scarlett', 'Johannson', '1984-11-22');
INSERT INTO test.kullanicilar (id, name, l_name, b_date) VALUES (uuid(), 'Ansel', 'Elgort', '1994-04-14');
INSERT INTO test.kullanicilar (id, name, l_name, b_date) VALUES (uuid(), 'Lily', 'James', '1989-05-05');
INSERT INTO test.kullanicilar (id, name, l_name, b_date) VALUES (uuid(), 'Jon', 'Hamm', '1971-04-10');
INSERT INTO test.kullanicilar (id, name, l_name, b_date) VALUES (uuid(), 'Eiza', 'Gonzalez', '1990-01-30');
INSERT INTO test.kullanicilar (id, name, l_name, b_date) VALUES (uuid(), 'Jamie', 'Foxx', '1967-12-13');
